name: Docker Artifact Development

on:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/media-api-dev:latest

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_NAME to lowercase
        run: echo "IMAGE_NAME=${{ env.REGISTRY }}/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/media-api:latest" >> $GITHUB_ENV

      - name: build and publish
        run: |
          docker build . --tag ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}

